name: Generate Neothesia Video from url raise volume

on:
  
  workflow_dispatch:
    inputs:
      input_path:
        description: 'Path to input mid file in the repo'
        required: true
        default: 'VirtuosicAMinorCycle.mid'
      gain:
        description: 'Enter gain value (e.g., 12dB, 20dB)'
        required: true
        default: '9dB'
        type: string
        
jobs:
  build-and-generate-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load cached FFmpeg
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/ffmpeg
            /usr/local/bin/ffprobe
          key: ${{ runner.os }}-ffmpeg-5.1.1

      - name: Install FFmpeg if not cached
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          VERSION=5.1.1
          RELEASE_NAME=ffmpeg-${VERSION}-amd64-static
          wget --timeout=8 --tries=30 https://www.johnvansickle.com/ffmpeg/old-releases/${RELEASE_NAME}.tar.xz
          tar -xf ${RELEASE_NAME}.tar.xz
          mv ${RELEASE_NAME}/ffmpeg ${RELEASE_NAME}/ffprobe /usr/local/bin/
          rm -rf ${RELEASE_NAME}


      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install FFmpeg dev libraries and pkg-config
        run: sudo apt-get update && sudo apt-get install -y pkg-config libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev libgl1 libglx-mesa0 libgl1-mesa-dri mesa-utils fluidsynth      
      - name: Clone Neothesia
        run: git clone https://github.com/PolyMeilex/Neothesia.git

      - name: Build neothesia-cli
        run: cargo build --release -p neothesia-cli
        working-directory: ./Neothesia/neothesia-cli

      - name: Download MIDI file
        run: wget -O input.mid "${{ github.event.inputs.input_path }}"      
      
      - name: Generate video from MIDI
        run: ./Neothesia/target/release/neothesia-cli input.mid video.mp4 --soundfont ./Neothesia/default.sf2

      - name: Raise volume
        # run: ffmpeg -i video.mp4 -af "loudnorm=I=-14:TP=-1:LRA=11" -c:v copy -c:a aac output.mp4
        run: ffmpeg -i video.mp4 -af "volume=${{ github.event.inputs.gain }}" -c:v copy -c:a aac output.mp4
  
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: neothesia-video
          path: output.mp4
